### get all users
GET {{ baseURL }}/users?limit=1&page=2&select=id

### get a user
GET {{ baseURL }}/users/a69412ca-d3dc-4537-9124-e59ff341e8e4



### create a user
POST {{ baseURL }}//users
Content-Type: application/json

{
  "username": "username2",
  "password": "password123456A.",
  "confirm_password": "password123456A."
}

### update a user
PATCH {{ baseURL }}/users/a69412ca-d3dc-4537-9124-e59ff341e8e4
Content-Type: application/json

{
    "email": "test@test.com"
}

### delete a user
DELETE {{ baseURL }}/users/a69412ca-d3dc-4537-9124-e59ff341e8e4


