name: deploy to prod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v4

      - name: Install npm dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: 📂 Sync files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "./dist/*"
          target: "/home/${{ secrets.SSH_USER }}/apps/joinus/backend/"

  post-ci:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Execute post-ci script
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/${{ secrets.SSH_USER }}/apps/joinus/backend && npm install && npm run post-ci
